[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "quick-tk-gui"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
]